### ISSUE TITLE
Add 64bit versions of programs to manifests

### ISSUE THREAD

**Issue by rasa** [ScoopInstaller/Nirsoft#1]
Per 
https://github.com/lukesampson/scoop/issues/2808
perhaps you could use the nirsoft.nlp file found in 
https://launcher.nirsoft.net/downloads/index.html
See https://github.com/rasa/scoops/blob/master/nlp2json.py for an example of parsing this file.

**Comment by MCOfficer** [comment]
first of all - thank you for suggesting this repo :)

unless i'm mistaken the .nlp file only exposes the executable paths as found inside the NirSoft directory, not their download url.
i could get the download urls from scraping the download pages (e.g. https://www.nirsoft.net/utils/app_audio_config.html), but that would likely get me temp-banned, given how strictly nirsoft.net is protected.

in my opinion, the best option seems to be to
1) parse the padfiles for the 32-bit downloads, as is done now
2) add `-x64` before the extension (e.g. `https://www.nirsoft.net/utils/appaudioconfig.zip` -> `https://www.nirsoft.net/utils/appaudioconfig-x64.zip`) to get the 64-bit downloads

i found nirsoft to be very consistent with naming schemes, so i expect this to work for all URLs (that have 64-bit versions).

**Comment by MCOfficer** [comment]
if an app had no 64-bit version, i used the 32-bit as "universal" one, so 64-bit users don't miss out.

feedback welcome.

**Comment by rasa** [comment]
Wow, thanks for jumping on this so quickly! I think your solution is great. I updated 
https://github.com/lukesampson/scoop/issues/2808 to indicate your bucket supports 64bit apps now.
