### ISSUE TITLE
Deprecate this bucket in favour of Ash258/Scoop-NirSoft

### ISSUE THREAD

**Issue by MCOfficer** [ScoopInstaller/Nirsoft#10]
Refs https://github.com/Ash258/Scoop-NirSoft

Once their bucket is out of WIP status, this one should be deprecated. My idea is to add a depreciation notice to the manifests, and keep updating the bucket for a couple more months, perhaps. 

Also make it public in lukesampson/scoop#2808

**Comment by rasa** [comment]
Since the referenced bucket has converted its manifests to YAML files, this is no longer a viable option as scoop doesn't support YAML files, atm.
