### ISSUE TITLE
regscanner@2.46: hash check failed

### ISSUE THREAD

**Issue by CypherNL** [ScoopInstaller/Nirsoft#11]
```
Updating 'regscanner' (2.45 -> 2.46)
Downloading new version
regscanner-x64.zip (93.0 KB) [=========================================================================================================] 100%
Checking hash of regscanner-x64.zip ... ERROR Hash check failed!
App:         scoop-nirsoft/regscanner
URL:         https://www.nirsoft.net/utils/regscanner-x64.zip
First bytes: 50 4B 03 04 14 00 02 00
Expected:    6ad09ab86b3b674f16585081eec01f97b15609fddaf7be8acb76fe15caa07de2
Actual:      f5a5b276a55b837ff16bdc918734b9358fcd54073b6428ba786471ef39860101
```

**Comment by MCOfficer** [comment]
Sorry i didn't notice this earlier.

For some reason, my server fails to update the bucket for the last couple weeks. I suspect it has been IP-banned from nirsoft.net. I'll contact them.

Edit: for the time being, i'll try to keep it uptodate manually.

**Comment by MCOfficer** [comment]
Apparently nirsoft's firewall blocks when there are too many TCP connections open. IDK how the updater reached that threshold, but he kindly unblocked me. Things are back to normal.
