### ISSUE TITLE
Please add shortcuts

### ISSUE THREAD

**Issue by brunnels** [ScoopInstaller/Nirsoft#3]
Please add shortcuts to all apps under NirSoft subdirectory ie:
```
    "architecture": {
        "64bit": {
            "url": "https://www.nirsoft.net/utils/shexview-x64.zip",
            "hash": "73248fb48ee6387cadbd6bdde5265cbef465cea7fca8f3b72eac5c408f4e7ccb",
            "shortcuts": [
                [
                    "shexview.exe",
                    "NirSoft\\ShellExView - Displays the details of shell extensions installed on your computer"
                ]
            ]
        },
        "32bit": {
            "url": "https://www.nirsoft.net/utils/shexview.zip",
            "hash": "b0f5e6bea715be67460d24e4ffe5256297ffd990cc4f5bfa902f9d5af0d1196d",
            "shortcuts": [
                [
                    "shexview.exe",
                    "NirSoft\\ShellExView - Displays the details of shell extensions installed on your computer"
                ]
            ]
        }
    },
```

**Comment by MCOfficer** [comment]
even though i own this bucket, i only use a small subset of its applications. Do you know if there are any CLI applications, or does nir only create ones with GUI?

**Comment by MCOfficer** [comment]
after the linked issue, i threw the idea of appending a description to the filename out the window. "ActiveX Compatibility Manager" is descriptive enough in my book.

A commit containing the actual updates will follow in ~ 30 minutes.

**Comment by MCOfficer** [comment]
You will have to reinstall your current applications for this to take effect. Thanks for the suggestion :)

**Comment by brunnels** [comment]
I'm not sure.  Every one I have used has a gui.

**Comment by brunnels** [comment]
Thank you!
