### ISSUE TITLE
Please persist the configuration and language files

### ISSUE THREAD

**Issue by Befod** [ScoopInstaller/Nirsoft#5]
Just like:
[SearchMyFiles](https://www.nirsoft.net/utils/search_my_files.html)\\
 ├ SearchMyFiles.exe
 ├ readme.txt
 ├**SearchMyFiles_lng.ini**
 └**SearchMyFiles.cfg**

**Comment by MCOfficer** [comment]
that might be pretty hard or even impossible. after a quick research, i wouldn't know how my manifest creation script should know which configuration files it should persist. the searchmyfiles download doesn't include them.

on a different note, isn't the _lng.ini file a localization thing? should that even be persisted?

**Comment by Befod** [comment]
The name of the configuration and language files is the same as that of the program.
All language files only have one name.
Just like:
- AaaBbbCcc.exe
- AaaBbbCcc.cfg
- AaaBbbCcc_lng.ini

**Comment by MCOfficer** [comment]
^i'm not entirely sure if that commit is all that was needed. feel free to hit me up if this issue should not have been closed.
